productsSample = [
    "Công thức hóa học của nước là gì?",
    "Phản ứng hóa học giữa acid và base là gì?",
    "Làm thế nào để cân bằng phương trình hóa học?",
    "Nguyên tố nào có số nguyên tử là 6, đó là Carbon?",
    "Phân biệt giữa liên kết ion và liên kết cộng hóa trị.",
    "Định nghĩa của pH là gì?",
    "Phản ứng oxi hóa khử là gì?",
    "Cấu trúc phân tử của Carbon Dioxide là gì?",
    "Làm thế nào để tính nồng độ mol của dung dịch?",
    "Nguyên tố nào là kim loại kiềm, chẳng hạn như Sodium?",
    "Phản ứng nhiệt phân là gì?",
    "Công thức hóa học của axit sulfuric là H2SO4.",
    "Làm thế nào để xác định số oxi hóa của một nguyên tố?",
    "Phân biệt giữa đồng vị và đồng phân.",
    "Nguyên tố nào có độ âm điện cao nhất, đó là Fluorine?",
    "Phản ứng trùng hợp là gì?",
    "Cấu trúc phân tử của Hydrogen Dioxide là gì?",
    "Làm thế nào để tính khối lượng mol của một chất?",
    "Nguyên tố nào là phi kim, chẳng hạn như Oxygen?",
    "Phản ứng thế là gì?",
    "Công thức hóa học của Sodium Chloride là NaCl.",
    "Làm thế nào để xác định cấu hình electron của một nguyên tố?",
    "Phân biệt giữa axit mạnh và axit yếu.",
    "Nguyên tố nào có số nguyên tử là 1, đó là Hydrogen?",
    "Phản ứng phân hủy là gì?",
    "Cấu trúc phân tử của Ammonia là gì?",
    "Làm thế nào để tính thể tích khí ở điều kiện tiêu chuẩn?",
    "Nguyên tố nào là kim loại chuyển tiếp, chẳng hạn như Iron?",
    "Phản ứng cộng là gì?",
    "Công thức hóa học của glucose là C6H12O6.",
    "Chemgenie là gì",
    "Trương Thành Đạt là ai",
    "Chemgenie có bao nhiêu người",
]

chitchatSample = [
    "Thời tiết hôm nay như thế nào?",
    "Ngoài trời nóng bao nhiêu?",
    "Ngày mai có mưa không?",
    "Nhiệt độ hiện tại là bao nhiêu?",
    "Bạn có thể cho tôi biết điều kiện thời tiết hiện tại không?",
    "Cuối tuần này có nắng không?",
    "Nhiệt độ hôm qua là bao nhiêu?",
    "Đêm nay trời sẽ lạnh đến mức nào?",
    "Ai là tổng thống đầu tiên của Hoa Kỳ?",
    "Chiến tranh thế giới thứ hai kết thúc vào năm nào?",
    "Bạn có thể kể cho tôi về lịch sử của internet không?",
    "Tháp Eiffel được xây dựng vào năm nào?",
    "Ai đã phát minh ra điện thoại?",
    "Tên của bạn là gì?",
    "Bạn có tên không?",
    "Tôi nên gọi bạn là gì?",
    "Ai đã tạo ra bạn?",
    "Bạn bao nhiêu tuổi?",
    "Bạn có thể kể cho tôi một sự thật thú vị không?",
    "Bạn có biết bất kỳ câu đố thú vị nào không?",
    "Màu sắc yêu thích của bạn là gì?",
    "Bộ phim yêu thích của bạn là gì?",
    "Bạn có sở thích nào không?",
    "Ý nghĩa của cuộc sống là gì?",
    "Bạn có thể kể cho tôi một câu chuyện cười không?",
    "Thủ đô của Pháp là gì?",
    "Dân số thế giới là bao nhiêu?",
    "Có bao nhiêu châu lục?",
    "Ai đã viết 'Giết con chim nhại'?",
    "Bạn có thể cho tôi một câu nói của Albert Einstein không?"
]